---
#Default region for deploying Custom Control Tower: Code Pipeline, Step functions, Lambda, SSM parameters, and StackSets
region: us-east-1
version: 2021-03-15
# Control Tower Custom Resources (Service Control Policies or CloudFormation)
resources:
  # -----------------------------------------------------------------------------
  # Organization Config Conformance Pack
  # -----------------------------------------------------------------------------
  - name: sra-config-conformance-pack-org-main-ssm
    resource_file: templates/sra-config-conformance-pack-org-main-ssm.yaml
    parameters:
      - parameter_key: pConformancePackName
        parameter_value: sra-operational-best-practices-for-encryption-and-keys
      - parameter_key: pConformancePackTemplateName
        parameter_value: Operational-Best-Practices-for-Encryption-and-Keys.yaml
      - parameter_key: pDeliveryS3KeyPrefix
        parameter_value: ''
      - parameter_key: pExcludedAccounts
        parameter_value: ''
      - parameter_key: pRegisterDelegatedAdminAccount
        parameter_value: 'Yes'
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - REPLACE_ME_ORG_MANAGEMENT_ACCOUNT_NAME
        