---
#Default region for deploying Custom Control Tower: Code Pipeline, Step functions, Lambda, SSM parameters, and StackSets
region: us-east-1
version: 2021-03-15

# Control Tower Custom Resources (Service Control Policies or CloudFormation)
resources:
  # -----------------------------------------------------------------------------
  # Config Management Account
  # -----------------------------------------------------------------------------
  - name: sra-config-management-account-main-ssm
    resource_file: templates/sra-config-management-account-main-ssm.yaml
    parameters:
      - parameter_key: pAllSupported
        parameter_value: 'true'
      - parameter_key: pCreateLambdaLogGroup
        parameter_value: 'false'
      - parameter_key: pFrequency
        parameter_value: 1hour
      - parameter_key: pIncludeGlobalResourceTypes
        parameter_value: 'true'
      - parameter_key: pKmsKeyArn
        parameter_value: ''
      - parameter_key: pLambdaLogGroupKmsKey
        parameter_value: ''
      - parameter_key: pLambdaLogGroupRetention
        parameter_value: '14'
      - parameter_key: pLambdaLogLevel
        parameter_value: INFO
      - parameter_key: pResourceTypes
        parameter_value: ''
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - REPLACE_ME_ORG_MANAGEMENT_ACCOUNT_NAME
