########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates an IAM role to configure the delegated administrator account -  - 'security_lake_org' solution in the repo,
  https://github.com/aws-samples/aws-security-reference-architecture-examples (sra-1u3sd7f8p)

Metadata:
  SRA:
    Version: 1.0
    Order: 2

Resources:
  rAWSServiceRoleForSecurityLakeResourceManagementSLR:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: resource-management.securitylake.amazonaws.com
