########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates an IAM role to configure the delegated administrator account -  - 'security_lake_org' solution in the repo,
  https://github.com/aws-samples/aws-security-reference-architecture-examples (sra-1u3sd7f8p)

Metadata:
  SRA:
    Version: 1.0
    Order: 2
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pSRASolutionName

      - Label:
          default: Role Properties
        Parameters:
          - pSecurityLakeSubscriberRoleName
          - pSecurityLakeOrgLambdaRoleName
          - pManagementAccountId
          - pLogArchiveAccountId

    ParameterLabels:
      pManagementAccountId:
        default: Organization Management Account ID
      pSecurityLakeOrgLambdaRoleName:
        default: Lambda Role Name
      pSecurityLakeSubscriberRoleName:
        default: Security Lake Query Subscriber Role Name
      pSRASolutionName:
        default: SRA Solution Name
      pLogArchiveAccountId:
        default: Log Archive Account ID

Parameters:
  pManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization Management Account ID
    Type: String
  pSecurityLakeOrgLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-security-lake-org-lambda
    Description: Lambda Role Name
    Type: String
  pSecurityLakeSubscriberRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-security-lake-query-subscriber
    Description: Security Lake Configuration IAM Role Name
    Type: String
  pSRASolutionName:
    AllowedValues: [sra-security-lake-org]
    Default: sra-security-lake-org
    Description: The SRA solution name. The default value is the folder name of the solution
    Type: String
  pLogArchiveAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Log Archive Account ID
    Type: String

Resources:
  rQuerySubscriberRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit role name provided
    Properties:
      RoleName: !Ref pSecurityLakeSubscriberRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn:
                  - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:role/${pSecurityLakeOrgLambdaRoleName}
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:root
      Path: '/'
      Policies:

        - PolicyName: sra-security-lake-org-subscriber-policy-ram
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowRamReadActions
                Effect: Allow
                Action:
                  - ram:ListResources
                  - ram:GetResourceShareInvitations
                Resource: '*'

              - Sid: AllowAcceptResourceShareInvitation
                Effect: Allow
                Action:
                  - ram:AcceptResourceShareInvitation
                Resource: !Sub arn:${AWS::Partition}:ram:*:${pLogArchiveAccountId}:resource-share-invitation/*
                Condition:
                  StringEquals:
                    ram:ShareOwnerAccountId: !Sub ${pLogArchiveAccountId}

        - PolicyName: sra-security-lake-org-subscriber-policy-glue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowGlueDatabaseActions
                Effect: Allow
                Action:
                  - glue:CreateDatabase
                  - glue:GetDatabase
                  - glue:GetDatabases
                Resource: 
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:catalog
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:database/amazon_security_lake_glue_db_*_subscriber
              - Sid: AllowGlueTableActions
                Effect: Allow
                Action:
                  - glue:CreateTable
                  - glue:GetPartitions
                  - glue:GetTable
                Resource: 
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:catalog
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_cloud_trail_mgmt_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:database/amazon_security_lake_glue_db_*_subscriber
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_sh_findings_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_lambda_execution_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_s3_data_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_route53_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_vpc_flow_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_eks_audit_2_0
                  - !Sub arn:${AWS::Partition}:glue:*:${AWS::AccountId}:table/amazon_security_lake_glue_db_*_subscriber/rl_amazon_security_lake_table_*_waf_2_0

        - PolicyName: sra-security-lake-org-policy-iam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowReadIamActions
                Effect: Allow
                Action: iam:GetRole
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*

        - PolicyName: sra-security-lake-org-policy-lakeformation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowGrantPermissions
                Effect: Allow
                Action: lakeformation:GrantPermissions
                Resource: "*"

      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName
