########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the Organization CloudTrail KMS Key

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: KMS Key Attributes
        Parameters:
          - pLoggingAccountId
          - pOrgPrimaryAccountId
          - pOrganizationCloudTrailKeyAlias
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pOrganizationCloudTrailKeyAlias:
        default: Organization CloudTrail KMS Key Alias
      pOrgPrimaryAccountId:
        default: Organization Primary Account ID
      pLoggingAccountId:
        default: Security Log Archive Account ID
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pOrganizationCloudTrailKeyAlias:
    Default: OrganizationCloudTrailKMSKey
    Description: Organization CloudTrail KMS Key Alias
    Type: String

  pOrgPrimaryAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization Primary Account ID
    Type: String

  pLoggingAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization log archive account ID
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rOrganizationCloudTrailKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Organization CloudTrail Key
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Sub ${pOrganizationCloudTrailKeyAlias}
        Statement:
          -
            Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"
          -
            Sid: Allow CloudTrail to encrypt logs
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: kms:GenerateDataKey*
            Resource: "*"
            Condition:
              StringLike:
                "kms:EncryptionContext:aws:cloudtrail:arn": !Sub "arn:${AWS::Partition}:cloudtrail:*:${pOrgPrimaryAccountId}:trail/*"
          -
            Sid: Allow CloudTrail to decrypt log files
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pOrgPrimaryAccountId}:root
            Action: kms:Decrypt
            Resource: "*"
            Condition:
              "Null":
                "kms:EncryptionContext:aws:cloudtrail:arn": "false"
          -
            Sid: Allow CloudTrail to describe key
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: kms:DescribeKey
            Resource: "*"
          -
            Sid: Allow alias creation during setup
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:CreateAlias
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub ${AWS::AccountId}
                "kms:ViaService": !Sub cloudformation.${AWS::Region}.amazonaws.com
          -
            Sid: Allow Log Archive and Primary account access
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pLoggingAccountId}:root
                - !Sub arn:${AWS::Partition}:iam::${pOrgPrimaryAccountId}:root
            Action: kms:Decrypt
            Resource: "*"
            Condition:
              "Null":
                "kms:EncryptionContext:aws:cloudtrail:arn": "false"
          -
            Sid: Allow account access
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - kms:DescribeKey
              - kms:Decrypt
            Resource: "*"
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rOrganizationCloudTrailKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${pOrganizationCloudTrailKeyAlias}
      TargetKeyId:
        !Ref rOrganizationCloudTrailKey

Outputs:
  oOrganizationCloudTrailKeyArn:
    Description: Organization CloudTrail KMS Key ARN
    Value: !GetAtt rOrganizationCloudTrailKey.Arn