---
#Default region for deploying Custom Control Tower: Code Pipeline, Step functions, Lambda, SSM parameters, and StackSets
region: us-east-1
version: 2021-03-15

# Control Tower Custom Resources (Service Control Policies or CloudFormation)
resources:
  # -----------------------------------------------------------------------------
  # AWS Config Aggregator Organization Solution
  # -----------------------------------------------------------------------------
  - name: sra-config-aggregator-org-main-ssm
    resource_file: templates/sra-config-aggregator-org-main-ssm.yaml
    parameters:
      - parameter_key: pAggregatorName
        parameter_value: sra-config-aggregator-org
      - parameter_key: pAggregatorRoleName
        parameter_value: sra-config-aggregator-org
      - parameter_key: pRegisterDelegatedAdminAccount
        parameter_value: 'Yes'
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - REPLACE_ME_ORG_MANAGEMENT_ACCOUNT_NAME