AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Lambda function and its execution role

Parameters:
  pSraRepoZipUrl:
    Type: String
    Default: 'https://github.com/liamschn/aws-security-reference-architecture-examples/archive/refs/heads/sra-genai.zip'
    Description: The S3 URL for the SRA solution zip file

  pDryRun:
    Type: String
    # TODO(liamschn): change the default to 'true' after done testing
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether to run in dry run mode or not

  pSRAExecutionRoleName:
    Type: String
    Default: 'sra-execution'
    Description: The name of the IAM role to use for execution of the SRA solution

  pDeployLambdaLogGroup:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: true or false; deploy lambda log group

  pLogGroupRetention:
    Type: Number
    Default: 30
    Description: The number of days to retain logs in the CloudWatch Log Group

  pLambdaLogLevel:
    Type: String
    Default: 'INFO'
    AllowedValues:
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'
    Description: The logging level for the Lambda function

  pSRASolutionName:
    AllowedValues: ['sra-bedrock-org']
    Description: The SRA solution name. The default value is the folder name of the solution
    Type: String
    Default: 'sra-bedrock-org'

  pSraSolutionVersion:
    Type: String
    Default: '1.0.0'
    Description: The version of the SRA solution

  pSRAStagingS3BucketName:
    # AllowedPattern: '^(?=^.{3,63}$)(?!.*[.-]{2})(?!.*[--]{2})(?!^(?:(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\.(?!$)|$)){4}$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)'
    ConstraintDescription:
      SRA Staging S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description:
      SRA Staging S3 bucket name for the artifacts relevant to solution. (e.g., lambda zips, CloudFormation templates) S3 bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    # Type: String
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sra/staging-s3-bucket-name

  pBedrockOrgLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-bedrock-org-lambda
    Description: Bedrock security control configuration Lambda role name
    Type: String
    AllowedValues: ['sra-bedrock-org-lambda']
 
  pBedrockModelEvalBucketRuleParams:
    Type: String
    # TODO(liamschn): update default value  of pBedrockModelEvalBucketRuleParams prior to production
    Default: '{"deploy": "true", "accounts": ["863518454635"], "regions": ["us-east-1", "us-west-2"], "input_params": {"BucketName": "test-mod-eval-bucket"}}'
    Description: Bedrock Model Evaluation Job Config Rule Parameters
    AllowedPattern: ^\{"deploy"\s*:\s*"(true|false)",\s*"accounts"\s*:\s*\[((?:"[0-9]+"(?:\s*,\s*)?)*)\],\s*"regions"\s*:\s*\[((?:"[a-z0-9-]+"(?:\s*,\s*)?)*)\],\s*"input_params"\s*:\s*(\{\s*(?:"BucketName"\s*:\s*"([a-zA-Z0-9-]*)"\s*)?})\}$
    ConstraintDescription: 
      "Must be a valid JSON string containing: 'deploy' (true/false), 'accounts' (array of account numbers), 
      'regions' (array of region names), and 'input_params' object (can be empty or contain 'BucketName'). Arrays can be empty. 
      Example: {\"deploy\": \"true\", \"accounts\": [\"123456789012\"], \"regions\": [\"us-east-1\"], \"input_params\": {\"s3BucketName\": \"my-bucket\"}} or
      {\"deploy\": \"false\", \"accounts\": [], \"regions\": [], \"input_params\": {}}"

  pBedrockIAMUserAccessRuleParams:
    Type: String
    # TODO(liamschn): update default value  of pBedrockIAMUserAccessRuleParams prior to production
    Default: '{"deploy": "true", "accounts": ["863518454635"], "regions": ["us-east-1", "us-west-2"], "input_params": {}}'
    Description: Bedrock IAM User Access Config Rule Parameters
    AllowedPattern: ^\{"deploy"\s*:\s*"(true|false)",\s*"accounts"\s*:\s*\[((?:"[0-9]+"(?:\s*,\s*)?)*)\],\s*"regions"\s*:\s*\[((?:"[a-z0-9-]+"(?:\s*,\s*)?)*)\],\s*"input_params"\s*:\s*(\{\s*(?:"BucketName"\s*:\s*"([a-zA-Z0-9-]*)"\s*)?})\}$
    ConstraintDescription: 
      "Must be a valid JSON string containing: 'deploy' (true/false), 'accounts' (array of account numbers), 
      'regions' (array of region names), and 'input_params' object/dict (can be empty or contain 'BucketName'). Arrays can be empty. 
      Example: {\"deploy\": \"true\", \"accounts\": [\"123456789012\"], \"regions\": [\"us-east-1\"], \"input_params\": {}} or
      {\"deploy\": \"false\", \"accounts\": [], \"regions\": [], \"input_params\": {}}"

  pBedrockGuardrailsRuleParams:
    Type: String
    # TODO(liamschn): update default value  of pBedrockIAMUserAccessRuleParams prior to production
    Default: '{"deploy": "true", "accounts": ["863518454635"], "regions": ["us-east-1", "us-west-2"], "input_params": {"content_filters": "true", "denied_topics": "true", "word_filters": "true", "sensitive_info_filters": "true", "contextual_grounding": "true"}}'
    Description: Bedrock Guardrails Config Rule Parameters
    AllowedPattern: ^\{"deploy"\s*:\s*"(true|false)",\s*"accounts"\s*:\s*\[((?:"[0-9]+"(?:\s*,\s*)?)*)\],\s*"regions"\s*:\s*\[((?:"[a-z0-9-]+"(?:\s*,\s*)?)*)\],\s*"input_params"\s*:\s*\{(\s*"content_filters"\s*:\s*"(true|false)")?(\s*,\s*"denied_topics"\s*:\s*"(true|false)")?(\s*,\s*"word_filters"\s*:\s*"(true|false)")?(\s*,\s*"sensitive_info_filters"\s*:\s*"(true|false)")?(\s*,\s*"contextual_grounding"\s*:\s*"(true|false)")?\s*\}\}$
    ConstraintDescription: >
      Must be a valid JSON string containing: 'deploy' (true/false), 'accounts' (array of account numbers),
      'regions' (array of region names), and 'input_params' object with optional parameters:
      'content_filters', 'denied_topics', 'word_filters', 'sensitive_info_filters', 'contextual_grounding'.
      Each parameter in 'input_params' should be either "true" or "false".
      Arrays can be empty. 
      Example: {"deploy": "true", "accounts": ["123456789012"], "regions": ["us-east-1"], "input_params": {"content_filters": "true", "denied_topics": "true", "word_filters": "true", "sensitive_info_filters": "true", "contextual_grounding": "false"}} or
      {"deploy": "false", "accounts": [], "regions": [], "input_params": {}}

  pBedrockVPCEndpointsRuleParams:
    Type: String
    # TODO(liamschn): update default value  of pBedrockIAMUserAccessRuleParams prior to production
    Default: '{"deploy": "true", "accounts": ["863518454635"], "regions": ["us-east-1", "us-west-2"], "input_params": {"check_bedrock": "true", "check_bedrock_agent": "true", "check_bedrock_agent_runtime": "true", "check_bedrock_runtime": "true"}}'
    Description: Bedrock VPC Endpoints Config Rule Parameters
    AllowedPattern: ^\{"deploy"\s*:\s*"(true|false)",\s*"accounts"\s*:\s*\[((?:"[0-9]+"(?:\s*,\s*)?)*)\],\s*"regions"\s*:\s*\[((?:"[a-z0-9-]+"(?:\s*,\s*)?)*)\],\s*"input_params"\s*:\s*\{(\s*"check_bedrock"\s*:\s*"(true|false)")?(\s*,\s*"check_bedrock_agent"\s*:\s*"(true|false)")?(\s*,\s*"check_bedrock_agent_runtime"\s*:\s*"(true|false)")?(\s*,\s*"check_bedrock_runtime"\s*:\s*"(true|false)")?\s*\}\}$
    ConstraintDescription: >
      Must be a valid JSON string containing: 'deploy' (true/false), 'accounts' (array of account numbers),
      'regions' (array of region names), and 'input_params' object with optional parameters:
      'check_bedrock', 'check_bedrock_agent', 'check_bedrock_agent_runtime', 'check_bedrock_runtime'.
      Each parameter in 'input_params' should be either "true" or "false".
      Arrays can be empty. 
      Example: {"deploy": "true", "accounts": ["123456789012"], "regions": ["us-east-1"], "input_params": {"check_bedrock": "true", "check_bedrock_agent": "true", "check_bedrock_agent_runtime": "true", "check_bedrock_runtime": "true"}} or
      {"deploy": "false", "accounts": [], "regions": [], "input_params": {}}

  pBedrockInvocationLoggingRuleParams:
    Type: String
    # TODO(liamschn): update default value  of pBedrockIAMUserAccessRuleParams prior to production
    Default: '{"deploy": "true", "accounts": ["863518454635"], "regions": ["us-east-1", "us-west-2"], "input_params": {"check_cloudwatch": "true", "check_s3": "true"}}'
    Description: Bedrock VPC Endpoints Config Rule Parameters
    AllowedPattern: ^\{"deploy"\s*:\s*"(true|false)",\s*"accounts"\s*:\s*\[((?:"[0-9]+"(?:\s*,\s*)?)*)\],\s*"regions"\s*:\s*\[((?:"[a-z0-9-]+"(?:\s*,\s*)?)*)\],\s*"input_params"\s*:\s*\{(\s*"check_cloudwatch"\s*:\s*"(true|false)")?(\s*,\s*"check_s3"\s*:\s*"(true|false)")?\}\}$
    ConstraintDescription: >
      Must be a valid JSON string containing: 'deploy' (true/false), 'accounts' (array of account numbers),
      'regions' (array of region names), and 'input_params' object with optional parameters:
      'check_cloudwatch', 'check_s3'.
      Each parameter in 'input_params' should be either "true" or "false".
      Arrays can be empty. 
      Example: {"deploy": "true", "accounts": ["123456789012"], "regions": ["us-east-1"], "input_params": {"check_cloudwatch": "true", "check_s3": "true"}} or
      {"deploy": "false", "accounts": [], "regions": [], "input_params": {}}


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SRA Solution Configuration
        Parameters:
          - pSraRepoZipUrl
          - pDryRun
          # - pRuleRegionsAccounts
          - pSRASolutionName
          - pSraSolutionVersion
          - pSRAStagingS3BucketName
      - Label:
          default: IAM Roles
        Parameters:
          - pSRAExecutionRoleName
          - pBedrockOrgLambdaRoleName
      - Label:
          default: Logging Configuration
        Parameters:
          - pDeployLambdaLogGroup
          - pLogGroupRetention
          - pLambdaLogLevel
      - Label:
          default: Bedrock Model Evaluation Bucket Rule
        Parameters:
          - pBedrockModelEvalBucketRuleParams
      - Label:
          default: Bedrock IAM User Access Rule
        Parameters:
          - pBedrockIAMUserAccessRuleParams
      - Label:
          default: Bedrock Guardrails Rule
        Parameters:
          - pBedrockGuardrailsRuleParams
      - Label:
          default: Bedrock VPC Endpoints Rule
        Parameters:
          - pBedrockVPCEndpointsRuleParams
      - Label:
          default: Bedrock Invocation Logging Rule
        Parameters:
          - pBedrockInvocationLoggingRuleParams

    ParameterLabels:
      pSraRepoZipUrl:
        default: SRA Repo Zip URL
      pDryRun:
        default: Dry Run
      pSRAExecutionRoleName:
        default: Stack Execution Role Name
      pDeployLambdaLogGroup:
        default: Deploy Lambda Log Group (true or false)
      pLogGroupRetention:
        default: Log Group Retention (days)
      pLambdaLogLevel:
        default: Lambda Log Level
      pSRASolutionName:
        default: SRA Solution Name
      pSraSolutionVersion:
        default: SRA Solution Version
      pSRAStagingS3BucketName:
        default: SRA Staging S3 Bucket Name
      pBedrockOrgLambdaRoleName:
        default: SRA Bedrock Org lambda role name
      pBedrockModelEvalBucketRuleParams:
        default: Bedrock Model Evaluation Job Config Rule Parameters
      pBedrockIAMUserAccessRuleParams:
        default: Bedrock IAM User Access Config Rule Parameters
      pBedrockGuardrailsRuleParams:
        default: Bedrock Guardrails Config Rule Parameters
      pBedrockVPCEndpointsRuleParams:
        default: Bedrock VPC Endpoints Config Rule Parameters
      pBedrockInvocationLoggingRuleParams:
        default: Bedrock Invocation Logging Config Rule Parameters

Resources:
  rBedrockOrgLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref pBedrockOrgLambdaRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        # TODO(liamschn): least privilege policies need to be created for this lambda role
        - arn:aws:iam::aws:policy/AdministratorAccess

  rBedrockOrgLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref pSRASolutionName
      Runtime: python3.12
      Role: !GetAtt rBedrockOrgLambdaRole.Arn
      Handler: app.lambda_handler
      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName
      Code:
        S3Bucket: !Ref pSRAStagingS3BucketName
        S3Key: !Sub ${pSRASolutionName}/lambda_code/${pSRASolutionName}.zip
      Timeout: 900
      MemorySize: 512

  rBedrockOrgLambdaCustomResource:
    Type: Custom::LambdaCustomResource
    Properties:
      ServiceToken: !GetAtt rBedrockOrgLambdaFunction.Arn
      SRA_REPO_ZIP_URL: !Ref pSraRepoZipUrl
      DRY_RUN: !Ref pDryRun
      EXECUTION_ROLE_NAME: !Ref pSRAExecutionRoleName
      LOG_GROUP_DEPLOY: !Ref pDeployLambdaLogGroup
      LOG_GROUP_RETENTION: !Ref pLogGroupRetention
      LOG_LEVEL: !Ref pLambdaLogLevel
      SOLUTION_NAME: !Ref pSRASolutionName
      SOLUTION_VERSION: !Ref pSraSolutionVersion
      SRA-BEDROCK-CHECK-EVAL-JOB-BUCKET: !Ref pBedrockModelEvalBucketRuleParams
      SRA-BEDROCK-CHECK-IAM-USER-ACCESS: !Ref pBedrockIAMUserAccessRuleParams
      SRA-BEDROCK-CHECK-GUARDRAILS: !Ref pBedrockGuardrailsRuleParams
      SRA-BEDROCK-CHECK-VPC-ENDPOINTS: !Ref pBedrockVPCEndpointsRuleParams

  rBedrockOrgLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref rBedrockOrgLambdaFunction
      Action: lambda:InvokeFunction
      Principal: cloudformation.amazonaws.com
      SourceArn: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stackSet/${AWS::StackName}/*'

Outputs:
  BedrockOrgLambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt rBedrockOrgLambdaFunction.Arn